Repository EatPic/EatPic-Spring, pull requests merged in 2025-07, with the labels that each got.

#21 Feature/19 댓글 작성/조회 기능
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/comment/controller/CommentRestController.java
  src/main/java/EatPic/spring/domain/comment/converter/CommentConverter.java
  src/main/java/EatPic/spring/domain/comment/dto/CommentRequestDTO.java
  src/main/java/EatPic/spring/domain/comment/dto/CommentResponseDTO.java
  src/main/java/EatPic/spring/domain/comment/repository/CommentRepository.java
  src/main/java/EatPic/spring/domain/comment/service/CommentService.java
  src/main/java/EatPic/spring/domain/comment/service/CommentServiceImpl.java
  src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/UserResponseDTO.java
  src/main/java/EatPic/spring/domain/user/repository/UserFollowRepository.java
  src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
  src/main/java/EatPic/spring/domain/user/service/UserCommandService.java
  src/main/java/EatPic/spring/domain/user/service/UserCommandServiceImpl.java
  src/main/java/EatPic/spring/global/common/BaseCode.java
  src/main/java/EatPic/spring/global/common/ReasonDTO.java
  src/main/java/EatPic/spring/global/common/response/ApiResponse.java
  src/main/java/EatPic/spring/global/config/SwaggerConfig.java
Labels: :sparkles: Features

#16 Feat: Calendar 기능 API 추가
  src/main/java/EatPic/spring/domain/calendar/controller/CalendarController.java
  src/main/java/EatPic/spring/domain/calendar/dto/CalendarDayResponse.java
  src/main/java/EatPic/spring/domain/calendar/service/CalendarService.java
  src/main/java/EatPic/spring/domain/card/entity/Card.java
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
Labels: :sparkles: Features

#8 Docs: 픽카드 기록하기 API 스웨거 작성
  .gradle/8.14.2/fileHashes/fileHashes.lock
  build.gradle
  src/main/java/EatPic/spring/domain/calendar/service/CalendarService.java
  src/main/java/EatPic/spring/domain/card/entity/Card.java
  src/main/java/EatPic/spring/domain/card/entity/CardImage.java
  src/main/java/EatPic/spring/domain/newcard/controller/NewcardController.java
  src/main/java/EatPic/spring/domain/newcard/dto/NewcardRequest.java
  src/main/java/EatPic/spring/domain/newcard/dto/NewcardResponse.java
  src/main/java/EatPic/spring/domain/newcard/repository/NewcardRepository.java
  src/main/java/EatPic/spring/domain/newcard/service/Impl/NewcardCommandServiceImpl.java
  src/main/java/EatPic/spring/domain/newcard/service/NewcardCommandService.java
  src/main/java/EatPic/spring/global/common/BaseResponse.java
  src/main/java/EatPic/spring/global/common/code/error/AuthErrorCode.java
  src/main/java/EatPic/spring/global/common/exception/AuthException.java
  src/main/resources/application-jwt.yml
  src/main/resources/application.yml
Labels: :memo: Docs

#37 Feat: 탐색 탭에서 모든 유저 리스트 조회
  src/main/java/EatPic/spring/domain/card/controller/SearchController.java
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/request/SearchRequestDTO.java
  src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
  src/main/java/EatPic/spring/domain/card/dto/response/SearchResponseDTO.java
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/card/service/SearchService.java
  src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
  src/main/java/EatPic/spring/domain/comment/repository/CommentRepository.java
  src/main/java/EatPic/spring/domain/reaction/repository/ReactionRepository.java
  src/main/java/EatPic/spring/global/common/BaseResponse.java
Labels: :sparkles: Features

#59 Feat: 홈화면 뱃지들 조회 api
  src/main/java/EatPic/spring/domain/badge/entity/Badge.java
  src/main/java/EatPic/spring/domain/badge/entity/ConditionType.java
  src/main/java/EatPic/spring/domain/badge/entity/ConditionValue.java
  src/main/java/EatPic/spring/domain/badge/repository/BadgeRepository.java
  src/main/java/EatPic/spring/domain/reaction/dto/ReactionResponseDTO.java
  src/main/java/EatPic/spring/domain/reaction/service/ReactionServiceImpl.java
  src/main/java/EatPic/spring/domain/user/controller/UserBadgeController.java
  src/main/java/EatPic/spring/domain/user/controller/UserController.java
  src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
  src/main/java/EatPic/spring/domain/user/converter/UserBadgeConverter.java
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/request/SignupRequestDTO.java
  src/main/java/EatPic/spring/domain/user/dto/response/SignupResponseDTO.java
  src/main/java/EatPic/spring/domain/user/dto/response/UserBadgeResponse.java
  src/main/java/EatPic/spring/domain/user/dto/response/UserResponseDTO.java
  src/main/java/EatPic/spring/domain/user/repository/UserBadgeRepository.java
  src/main/java/EatPic/spring/domain/user/service/UserBadgeService.java
  src/main/java/EatPic/spring/domain/user/service/UserCommandService.java
  src/main/java/EatPic/spring/domain/user/service/UserCommandServiceImpl.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
Labels: :sparkles: Features

#61 Feat: 뱃지 상세 조회하기 api 추가
  src/main/java/EatPic/spring/domain/user/controller/UserBadgeController.java
  src/main/java/EatPic/spring/domain/user/converter/UserBadgeConverter.java
  src/main/java/EatPic/spring/domain/user/dto/response/UserBadgeResponse.java
  src/main/java/EatPic/spring/domain/user/repository/UserBadgeRepository.java
  src/main/java/EatPic/spring/domain/user/service/UserBadgeService.java
Labels: :sparkles: Features

#62 Feat: 검색 범위가 전체인 경우에서 계정 검색
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/EatPic/spring/domain/card/controller/SearchController.java
  src/main/java/EatPic/spring/domain/card/dto/request/CardCreateRequest.java
  src/main/java/EatPic/spring/domain/card/dto/request/SearchRequestDTO.java
  src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
  src/main/java/EatPic/spring/domain/card/dto/response/SearchResponseDTO.java
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
  src/main/java/EatPic/spring/domain/card/service/SearchService.java
  src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/response/UserResponseDTO.java
  src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
  src/main/java/EatPic/spring/global/common/BaseResponse.java
  src/main/java/EatPic/spring/global/common/code/status/ErrorStatus.java
Labels: :sparkles: Features

#68 Feat: home 오늘 식사 현황 불러오기
  src/main/java/EatPic/spring/domain/card/controller/CardController.java
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/card/service/CardService.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
Labels: :sparkles: Features

#78 Refactor: 홈 부분 리펙토링(응답통일 등)
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
  src/main/java/EatPic/spring/domain/greetingMessage/controller/GreetingController.java
  src/main/java/EatPic/spring/domain/notification/controller/NotificationController.java
Labels: :recycle: Refactor

#84 Chore: CICD deploy
  .github/workflows/dev_deploy.yml
  .gitignore
  Dockerfile
  src/main/java/EatPic/spring/domain/card/entity/Card.java
  src/main/resources/application-jwt.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/EatPic/spring/ApplicationTests.java
Labels: :sparkles: Features, 🧑🏻‍🔧CI

#79 Feat: 프로필 화면 API
  src/main/java/EatPic/spring/domain/card/controller/CardController.java
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/card/service/CardService.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
  src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/response/UserResponseDTO.java
  src/main/java/EatPic/spring/domain/user/repository/UserFollowRepository.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
Labels: :sparkles: Features
