Repository EatPic/EatPic-Spring, pull requests merged in 2025-08, with the labels that each got.

#103 Feat: S3 설정 + cors 설정
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/EatPic/spring/domain/badge/service/BadgeService.java
  src/main/java/EatPic/spring/domain/card/controller/CardController.java
  src/main/java/EatPic/spring/domain/card/controller/SearchController.java
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/request/CardCreateRequest.java
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/card/service/CardService.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
  src/main/java/EatPic/spring/domain/card/service/SearchService.java
  src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
  src/main/java/EatPic/spring/domain/user/controller/UserController.java
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/request/SignupRequestDTO.java
  src/main/java/EatPic/spring/domain/user/dto/response/SignupResponseDTO.java
  src/main/java/EatPic/spring/domain/user/entity/Role.java
  src/main/java/EatPic/spring/domain/user/entity/User.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
  src/main/java/EatPic/spring/domain/uuid/entity/Uuid.java
  src/main/java/EatPic/spring/domain/uuid/repository/UuidRepository.java
  src/main/java/EatPic/spring/global/aws/s3/AmazonS3Manager.java
  src/main/java/EatPic/spring/global/common/code/status/ErrorStatus.java
  src/main/java/EatPic/spring/global/common/exception/ExceptionAdvice.java
  src/main/java/EatPic/spring/global/common/exception/GeneralException.java
  src/main/java/EatPic/spring/global/config/AmazonConfig.java
  src/main/java/EatPic/spring/global/config/CorsConfig.java
  src/main/java/EatPic/spring/global/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/EatPic/spring/global/config/SecurityConfig.java
Labels: :recycle: Refactor, :sparkles: Features

#104 Feat: 팔로우한 사용자 중에서 계정으로 검색
  src/main/java/EatPic/spring/domain/card/controller/SearchController.java
  src/main/java/EatPic/spring/domain/card/service/SearchService.java
  src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
  src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
Labels: :sparkles: Features

#109 Feat: 이메일 회원 가입
  src/main/java/EatPic/spring/domain/user/controller/UserController.java
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/request/SignupRequestDTO.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
Labels: :sparkles: Features

#105 Feat: 검색 범위가 전체인 경우에서 해시태그 검색하기
  src/main/java/EatPic/spring/domain/card/controller/SearchController.java
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/request/CardCreateRequest.java
  src/main/java/EatPic/spring/domain/card/dto/response/SearchResponseDTO.java
  src/main/java/EatPic/spring/domain/card/entity/Card.java
  src/main/java/EatPic/spring/domain/card/repository/CardHashtagRepository.java
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/card/repository/HashtagRepository.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
  src/main/java/EatPic/spring/domain/card/service/SearchService.java
  src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
  src/main/java/EatPic/spring/global/config/SecurityConfig.java
Labels: :sparkles: Features

#106 Feat: 검색범위가 유저가 팔로우한 사용자인 경우에서 해시태그 검색하기
  src/main/java/EatPic/spring/domain/card/controller/CardController.java
  src/main/java/EatPic/spring/domain/card/controller/SearchController.java
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/repository/HashtagRepository.java
  src/main/java/EatPic/spring/domain/card/service/SearchService.java
  src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
  src/main/java/EatPic/spring/domain/user/repository/UserFollowRepository.java
Labels: :recycle: Refactor, :sparkles: Features

#111 Refactor: 이메일 로그인
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/EatPic/spring/domain/notification/service/NotificationService.java
  src/main/java/EatPic/spring/domain/user/controller/RoleTestController.java
  src/main/java/EatPic/spring/domain/user/controller/UserController.java
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/UserInfoDTO.java
  src/main/java/EatPic/spring/domain/user/dto/request/LoginRequestDTO.java
  src/main/java/EatPic/spring/domain/user/dto/response/LoginResponseDTO.java
  src/main/java/EatPic/spring/domain/user/dto/response/SignupResponseDTO.java
  src/main/java/EatPic/spring/domain/user/entity/User.java
  src/main/java/EatPic/spring/domain/user/exception/UserErrorCode.java
  src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
  src/main/java/EatPic/spring/global/common/BaseErrorCode.java
  src/main/java/EatPic/spring/global/common/code/BaseCode.java
  src/main/java/EatPic/spring/global/common/code/ErrorReasonDTO.java
  src/main/java/EatPic/spring/global/common/code/ReasonDTO.java
  src/main/java/EatPic/spring/global/common/code/status/ErrorStatus.java
  src/main/java/EatPic/spring/global/config/Properties/Constants.java
  src/main/java/EatPic/spring/global/config/Properties/JwtProperties.java
  src/main/java/EatPic/spring/global/config/SecurityConfig.java
  src/main/java/EatPic/spring/global/config/SwaggerConfig.java
  src/main/java/EatPic/spring/global/config/jwt/JwtAuthenticationFilter.java
  src/main/java/EatPic/spring/global/config/jwt/JwtTokenProvider.java
Labels: :recycle: Refactor

#115 Feat: 유저 아이디(nameId) 중복 검사
  src/main/java/EatPic/spring/domain/user/controller/UserController.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
Labels: :sparkles: Features

#119 refactor: 로그인한 유저 수정
  src/main/java/EatPic/spring/domain/bookmark/controller/BookmarkController.java
  src/main/java/EatPic/spring/domain/bookmark/service/BookmarkService.java
  src/main/java/EatPic/spring/domain/bookmark/service/BookmarkServiceImpl.java
  src/main/java/EatPic/spring/domain/card/controller/CardController.java
  src/main/java/EatPic/spring/domain/card/service/CardService.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
  src/main/java/EatPic/spring/domain/comment/controller/CommentRestController.java
  src/main/java/EatPic/spring/domain/comment/service/CommentService.java
  src/main/java/EatPic/spring/domain/comment/service/CommentServiceImpl.java
  src/main/java/EatPic/spring/domain/greetingMessage/controller/GreetingController.java
  src/main/java/EatPic/spring/domain/greetingMessage/service/GreetingService.java
  src/main/java/EatPic/spring/domain/reaction/controller/ReactionRestController.java
  src/main/java/EatPic/spring/domain/reaction/service/ReactionService.java
  src/main/java/EatPic/spring/domain/reaction/service/ReactionServiceImpl.java
  src/main/java/EatPic/spring/domain/reportHistory/controller/ReportController.java
  src/main/java/EatPic/spring/domain/reportHistory/service/ReportService.java
  src/main/java/EatPic/spring/domain/reportHistory/service/ReportServiceImpl.java
  src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
Labels: :recycle: Refactor

#120 Feat: 해시태그 검색 시 해당 해시태그를 포함한 픽카드 리스트 조회
  src/main/java/EatPic/spring/domain/card/controller/CardController.java
  src/main/java/EatPic/spring/domain/card/controller/SearchController.java
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/response/SearchResponseDTO.java
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/card/repository/HashtagRepository.java
  src/main/java/EatPic/spring/domain/card/service/CardService.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
  src/main/java/EatPic/spring/domain/card/service/SearchService.java
  src/main/java/EatPic/spring/domain/card/service/SearchServiceImpl.java
  src/main/java/EatPic/spring/domain/comment/repository/CommentRepository.java
  src/main/java/EatPic/spring/domain/reaction/repository/ReactionRepository.java
  src/main/java/EatPic/spring/global/common/BaseErrorCode.java
Labels: :recycle: Refactor, :sparkles: Features

#122 Feat: 차단한 유저 카드 피드에서 제외
  src/main/java/EatPic/spring/domain/card/repository/CardRepository.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
Labels: :sparkles: Features

#128 Refactor: ApiResponse 수정
  src/main/java/EatPic/spring/domain/user/controller/UserController.java
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/response/CheckNicknameResponseDTO.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
  src/main/java/EatPic/spring/global/common/code/status/ErrorStatus.java
Labels: :recycle: Refactor

#135 Refactor: 에러 처리 및 UserConverter 수정
  src/main/java/EatPic/spring/domain/user/converter/UserConverter.java
  src/main/java/EatPic/spring/domain/user/dto/response/SignupResponseDTO.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
Labels: :recycle: Refactor

#137 Feat: 유저 프로필 이미지 수정 API
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
  src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
  src/main/java/EatPic/spring/domain/user/entity/User.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
Labels: :sparkles: Features

#141 Refactor: 픽카드 기록하기 파라미터로 받아오는 request 수정
  src/main/java/EatPic/spring/domain/card/controller/CardController.java
  src/main/java/EatPic/spring/domain/card/dto/request/CardCreateRequest.java
  src/main/java/EatPic/spring/domain/card/service/CardService.java
  src/main/java/EatPic/spring/domain/card/service/CardServiceImpl.java
Labels: :bug: Bug, :recycle: Refactor

#144 Refactor: nameId 추가
  src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
  src/main/java/EatPic/spring/domain/reaction/controller/ReactionRestController.java
Labels: :recycle: Refactor

#148 refactor: 피드 조회 datetime 형식 수정
  src/main/java/EatPic/spring/domain/card/controller/CardController.java
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
Labels: :recycle: Refactor

#149 Feat: 유저 소개글 수정 API
  src/main/java/EatPic/spring/domain/user/controller/UserRestController.java
  src/main/java/EatPic/spring/domain/user/dto/request/UserRequest.java
  src/main/java/EatPic/spring/domain/user/dto/response/UserResponseDTO.java
  src/main/java/EatPic/spring/domain/user/entity/User.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
Labels: :recycle: Refactor

#169 Refactor: date time 제공 수정
  src/main/java/EatPic/spring/domain/card/converter/CardConverter.java
  src/main/java/EatPic/spring/domain/card/dto/response/CardResponse.java
Labels: :recycle: Refactor

#186 Feat: refresh token 재발급
  src/main/java/EatPic/spring/domain/user/controller/UserController.java
  src/main/java/EatPic/spring/domain/user/dto/response/RefreshTokenResponseDTO.java
  src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
  src/main/java/EatPic/spring/domain/user/service/UserService.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
  src/main/java/EatPic/spring/global/config/Properties/JwtProperties.java
  src/main/java/EatPic/spring/global/config/jwt/JwtTokenProvider.java
Labels: :sparkles: Features

#188 Bug: 메서드에 @Transactional 어노테이션을 추가
  src/main/java/EatPic/spring/domain/user/repository/UserRepository.java
  src/main/java/EatPic/spring/domain/user/service/UserServiceImpl.java
Labels: :bug: Bug
